wopsaccount:
  greeting: "Welcome to the integration env of account service"
spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:7002/wops_account_integration
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
